CC = gcc
CXX = g++
IDIR = ../build
LDIR = ../build
CFLAGS = -I$(IDIR) -L$(LDIR) -O3

DEPS = cblas.h
OBJS = test_sgemm.o
LIBS = -lcblas -lm

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $^ $(CFLAGS)

test_sgemm: $(OBJS)
	$(CXX) -o $@ $^ $(CFLAGS) $(LIBS)

